# Generated by Django 5.1.4 on 2025-01-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('basic', 'Basic User'), ('organiser', 'Event Organiser'), ('musician', 'Musician/Performer')], default='basic', max_length=20),
        ),
    ]
