# Generated by Django 5.1.4 on 2025-01-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('basic', 'Basic User'), ('organiser', 'Event Organiser'), ('musician', 'Musician/Band')], default='basic', max_length=20),
        ),
    ]
