# Generated by Django 5.1.4 on 2025-01-11 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at']},
        ),
    ]
