# Generated by Django 5.1.4 on 2025-01-15 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_options'),
        ('profiles', '0002_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='musician',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'musician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_as_musician', to='profiles.profile'),
        ),
    ]
