# Generated by Django 5.1.4 on 2025-01-15 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_musician'),
        ('profiles', '0002_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='musician',
            field=models.ForeignKey(blank=True, help_text="Optional. Must be a user with role='musician'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_as_musician', to='profiles.profile'),
        ),
    ]
