# Generated by Django 5.1.4 on 2025-01-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_musician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='musician',
        ),
    ]
