# Generated by Django 5.1.4 on 2025-01-15 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_musician'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='musicians',
            field=models.ManyToManyField(blank=True, related_name='musician_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
