# Generated by Django 5.1.4 on 2025-01-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_musicians'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('ORCHESTRA', 'Orchestra'), ('FESTIVAL', 'Festival'), ('GIG', 'Gig'), ('PARTY', 'Party'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
