# Generated by Django 5.1.4 on 2025-01-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('CONFERENCE', 'Conference'), ('MEETUP', 'Meetup'), ('WORKSHOP', 'Workshop'), ('PARTY', 'Party'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
